image: alpine:latest

pages:
  stage: deploy
  script:
  - mkdir public
  - cp -r *.html content *.css public/
  - cp -r .well-known public/ # uncomment this line to use letsencrypt challenge
  artifacts:
    paths:
    - public
  only:
  - master
